name: Test

permissions:
  contents: write
  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-cache:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    container:
      image: ubuntu:latest
      options: --user root

    steps:
    - name: Create test file
      run: touch /tmp/1.test
    
    - name: Save Cache
      uses: actions/cache/save@v3
      with:
        path: |
          /tmp/
        key: testcache1
        
    - name: Clear test file
      run: rm /tmp/1.test
      
    - name: List /tmp/
      run: ls -laR /tmp/
      
    - name: Restore Cached Debs
      id: cache-debs-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          /tmp/
        key: testcache1
        
    - name: List /tmp/ Again
      run: ls -laR /tmp/
